keycloak:
  replicas: 1
  image: quay.io/keycloak/keycloak:23.0

  # Admin credentials (CHANGE THESE!)
  adminUser: admin
  adminPassword: admin-change-this-password

  # Database configuration
  database:
    vendor: postgres
    host: postgres-service.keycloak-db.svc.cluster.local
    port: 5432
    database: keycloak
    username: keycloak
    password: keycloak-secure-password-123  # Must match PostgreSQL password

  # Resource limits (optional)
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

# Ingress configuration
domain: keycloak.ltu-m7011e-johan.se  # Change to your domain
email: your.email@ltu.se              # Change to your email
certIssuer: letsencrypt-staging       # Use letsencrypt-prod for production
