apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana 
  template:
     metadata:
       annotations:
         timestamp: {{ now | quote }}
       labels:
         app: grafana
     spec:
       containers:
       - name: grafana
         image: {{ .Values.GrafanaImage | quote }}
         imagePullPolicy: "Always"
         ports:
           - containerPort: 3000
