apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service-management
  labels:
    app: rabbitmq
spec:
  selector:
    app: rabbitmq 
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 15672
      targetPort: 15672
      nodePort: 30001
