apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  labels:
    app: keycloak 
data:
  TZ: {{ .Values.Timezone | quote }}
  KEYCLOAK_ADMIN: {{ .Values.KeycloakAdmin | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.KeycloakAdminPassword | quote }}
  KC_HTTPS_PORT: "443"
  KC_HOSTNAME_URL: {{ .Values.KeycloakURL | quote }}
  KC_PROXY: "edge"
  KC_DB_URL_HOST: {{ .Values.DBHost | quote }}
  KC_DB_URL_PORT: "5432"
  KC_DB: "postgres"
  KC_DB_PASSWORD: {{ .Values.DBPassword | quote }}
  KC_DB_USERNAME: {{ .Values.DBUser | quote }}
