apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_USER: {{ .Values.DBUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.DBPassword | quote }}
  PGDATA: /var/lib/postgresql/data
  TZ: {{ .Values.Timezone | quote }}
