apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  labels:
    app: keycloak 
spec:
  selector:
    app: keycloak
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
