apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: keycloak 
data:
  POSTGRES_USER: {{ .Values.DBUser | quote }} 
  POSTGRES_PASSWORD: {{ .Values.DBPassword | quote }}
  POSTGRES_DB: "keycloak"
  PGDATA: /var/lib/postgresql/data/keycloak
  TZ: {{ .Values.Timezone | quote }}
  TS_TUNE_MAX_CONNS: "1000"
