apiVersion: v1
kind: Service
metadata:
  name: minio-service-api
  labels:
    app: minio
spec:
  selector:
    app: minio
  ports:
    - name: http
      protocol: TCP
      port: 9000
      targetPort: 9000
