apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  name: minio-ingress-api
  annotations:
    kubernetes.io/ingress.class: traefik 
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  rules:
  - host: {{ .Values.APIHostname | quote }} 
    http:
      paths:
        - pathType: Prefix 
          path: /
          backend:
            service:
              name: minio-service-api
              port: 
                number: 9000
  tls:
    - secretName: minio-api-tls
      hosts:
        - {{ .Values.APIHostname | quote }} 
