apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-config
  labels:
    app: minio
data:
  MINIO_ROOT_USER: {{ .Values.Username | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.Password | quote }} 
  MINIO_SERVER_URL: "https://{{ .Values.APIHostname }}"
