apiVersion: v1
kind: Service
metadata:
  name: minio-service-console
  labels:
    app: minio
spec:
  selector:
    app: minio 
  ports:
    - name: http
      protocol: TCP
      port: 9001
      targetPort: 9001
