apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # Add Git repositories here if using private repos
  # repositories: |
  #   - url: https://github.com/your-org/your-repo

  # Timeout settings
  timeout.reconciliation: 180s

  # Application settings
  application.instanceLabelKey: argocd.argoproj.io/instance
