---
# This ConfigMap will be created first by Helm, then patched by the install job
# The install job patches it to ensure the URL is set correctly after ArgoCD is installed
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # Timeout settings
  timeout.reconciliation: 180s

  # Application settings
  application.instanceLabelKey: argocd.argoproj.io/instance

  # Add Git repositories here if using private repos
  # repositories: |
  #   - url: https://github.com/your-org/your-repo
