apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service-api
  labels:
    app: rabbitmq 
spec:
  selector:
    app: rabbitmq
  type: NodePort
  ports:
    - name: amqp 
      protocol: TCP
      port: 5672
      targetPort: 5672
      nodePort: 30000
